version: "3"

services:
  users-svc:
    image: "users-svc:dev"
    container_name: "users-svc"
    build:
      context: "./microservices/users-svc"
    networks:
      - "frontend"
      - "backend"
      - "usersdomain"
    expose:
      - "50051"
    depends_on:
      - "users-db"
    environment:
      NODE_ENV: "test"
      GRPC_HOST: "0.0.0.0"
      GRPC_PORT: "50051"
      DB_HOST: "users-db"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DATABASE: "postgres"
      DB_SCHEMA: "public"
      DB_SYNC: "true"
    healthcheck:
      test: [ "CMD", "/bin/grpc_health_probe", "-addr=:50051" ]
      interval: 30s
      timeout: 10s
      retries: 5
    # restart: "on-failure"
  savings-svc:
    image: "savings-svc:dev"
    container_name: "savings-svc"
    build:
      context: "./microservices/savings-svc"
    networks:
      - "frontend"
      - "backend"
      - "savingsdomain"
    expose:
      - "50051"
    depends_on:
      - "savings-db"
    environment:
      NODE_ENV: "test"
      GRPC_HOST: "0.0.0.0"
      GRPC_PORT: "50051"
      DB_HOST: "savings-db"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DATABASE: "postgres"
      DB_SCHEMA: "public"
      DB_SYNC: "true"
    healthcheck:
      test: [ "CMD", "/bin/grpc_health_probe", "-addr=:50051" ]
      interval: 30s
      timeout: 10s
      retries: 5
    # restart: "on-failure"

  task-schedulings-svc:
    image: "task-schedulings-svc:dev"
    container_name: "task-schedulings-svc"
    build:
      context: "./microservices/task-schedulings-svc"
    networks:
      - "backend"
      - "savingsdomain"
      - "queuedomain"
    expose:
      - "50051"
    depends_on:
      - "savings-db"
      - "rabbitmq"
    environment:
      NODE_ENV: "test"
      DB_HOST: "savings-db"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DATABASE: "postgres"
      DB_SCHEMA: "public"
      DB_SYNC: "true"
      # CRON_EXPRESSION: "59 23 * * *"
      CRON_EXPRESSION: "*/10 * * * * *"
      NUMBER_USER_OF_PART: 5
      RABBIT_URL: "amqp://guest:guest@rabbitmq:5672/"
      QUEUE_SAVING_NAME: "savings"
    healthcheck:
      test: [ "CMD", "/bin/grpc_health_probe", "-addr=:50051" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "on-failure"

  workers-svc:
    image: "workers-svc:dev"
    container_name: "workers-svc"
    build:
      context: "./microservices/workers-svc"
    networks:
      - "backend"
      - "savingsdomain"
      - "queuedomain"
    expose:
      - "50051"
    depends_on:
      - "savings-db"
      - "rabbitmq"
    environment:
      NODE_ENV: "test"
      DB_HOST: "savings-db"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DATABASE: "postgres"
      DB_SCHEMA: "public"
      DB_SYNC: "true"
      SAVING_FIXED_INTEREST: 7
      NUMBER_USER_OF_PART: 5
      RABBIT_URL: "amqp://guest:guest@rabbitmq:5672/"
      QUEUE_SAVING_NAME: "savings"
    healthcheck:
      test: [ "CMD", "/bin/grpc_health_probe", "-addr=:50051" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: "on-failure"

  api-gateway:
    image: "api-gateway:dev"
    container_name: "api-gateway"
    build:
      context: "./api-gateway"
    networks:
      - "frontend"
    ports:
      - "3000:3000"
    depends_on:
      - "users-svc"
      - "savings-svc"
    environment:
      NODE_ENV: "test"
      GRAPHQL_PORT: "3000"
      JWT_ACCESSTOKEN_SECRET: "VtWeuJo5cPrH1gzvLX0HwPkcbVVeMkV0/a2JFeP3hGE="
      JWT_REFRESHTOKEN_SECRET: "tPQz6vb7nJDilma85OQExilvgZX+QyEf1CL95DmfBLA="
      JWT_ISSUER: "application"
      JWT_AUDIENCE: "public"
      SAVINGS_SVC_URL: "savings-svc:50051"
      USERS_SVC_URL: "users-svc:50051"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "localhost:3000/healthz -q -O - > /dev/null 2>&1"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    # restart: "on-failure"

  users-db:
    image: "postgres"
    container_name: "users-db"
    networks:
      - "usersdomain"
    expose:
      - "5432"
    ports:
      - "5551:5432"
    volumes:
      - usersdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres'" ]
      interval: 30s
      timeout: 30s
      retries: 3
    # restart: "on-failure"

  savings-db:
    image: "postgres"
    container_name: "savings-db"
    networks:
      - "savingsdomain"
    expose:
      - "5432"
    ports:
      - "5552:5432"
    volumes:
      - savingsdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres'" ]
      interval: 30s
      timeout: 30s
      retries: 3
    # restart: "on-failure"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    expose:
      - "5672"
    ports:
      - 5553:5672
      - 5554:15672
    volumes:
      - rabbitmqdata/:/var/lib/rabbitmq/
      - rabbitmqlog:/var/log/rabbitmq
    networks:
      - queuedomain
    # default rabbitmq user & pass: guest

networks:
  frontend:
  backend:
  usersdomain:
  savingsdomain:
  queuedomain:


volumes:
  usersdata:
  savingsdata:
  rabbitmqdata:
  rabbitmqlog:
