---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-schedulings-svc
  namespace: dev
  labels:
    app: task-schedulings-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-schedulings-svc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: task-schedulings-svc
    spec:
      containers:
        - name: task-schedulings-svc
          image: 'task-schedulings-svc:latest'
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 150Mi
            limits:
              cpu: 100m
              memory: 300Mi
          envFrom:
            - configMapRef:
                name: task-schedulings-svc
            - secretRef:
                name: smtp
          ports:
            - name: http
              containerPort: 50051
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - '/bin/grpc_health_probe'
                - '-addr=:50051'
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - '/bin/grpc_health_probe'
                - '-addr=:50051'
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
      terminationGracePeriodSeconds: 60
