version: "3"

services:

  savings-svc:
    image: "savings-svc:dev"
    container_name: "savings-svc"
    build:
      context: "./microservices/savings-svc"
    networks:
      - "savings-svc"
    expose:
      - "50051"
    depends_on:
      - "savings-db"
    environment:
      NODE_ENV: "test"
      GRPC_HOST: "0.0.0.0"
      GRPC_PORT: "50051"
      DB_HOST: "savings-db"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DATABASE: "postgres"
      DB_SCHEMA: "public"
      DB_SYNC: "true"
    healthcheck:
      test: [ "CMD", "/bin/grpc_health_probe", "-addr=:50051" ]
      interval: 30s
      timeout: 10s
      retries: 5
    # restart: "on-failure"
  db:
    image: "postgres:12-alpine"
    networks:
      - "savings-svc"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres'" ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"

networks:
  savings-svc:
