---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway
  namespace: dev
  labels:
    app: api-gateway
data:
  NODE_ENV: 'development'
  GRAPHQL_PORT: '3000'
  SAVINGS_SVC_URL: <SAVINGS_SVC>:50051
  WORKERS_SVC_URL: <WORKERS_SVC>:50051
  USERS_SVC_URL: <USERS_SVC>:50051
  TASK_SCHEDULINGS_SVC_URL: <TASK_SCHEDULINGS_SVC>:50051
