name: Nest RC Worker Build

on:
  push:
    branches:
      - "main"
    tags:
      - "*-rc.worker"

jobs:
  build:
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Get tag name
        id: get_tag
        run: echo ${GITHUB_REF/refs\/tags\//}
      
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: ${{ github.actor }}
          text: Build ${{ github.workflow }} on ${{ github.ref }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
