name: Nest RC Worker Build

on:
  push:
    branches:
      - "main"
    tags:
      - "*-rc.worker"

jobs:
  build:
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Notify Slack Build Starting
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          channel_id: C04MQ96V738
          status: STARTING
          color: warning

      - name: Get tag name
        id: get_tag
        run: echo ${GITHUB_REF/refs\/tags\//}
      
      - name: Notify Slack Build Success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          channel_id: C04MQ96V738
          status: SUCCESS
          color: good

      - name: Notify Slack Build Failed
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          channel_id: C04MQ96V738
          status: FAILED
          color: danger
