name: Nest RC Worker Build

on:
  push:
    branches:
      - "main"
    tags:
      - "*-worker-rc"

jobs:
  build:
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Get tag name
        id: get_tag
        run: echo ${GITHUB_REF/refs\/tags\//}
